### PR TITLE
Port d-a-v PR branch recurrentscheduledfunctions to circular_queue_mp

### PR DESCRIPTION
**Pull request by dok-net**
Room for improvement:
The circular queue is created with SCHEDULED_FN_MAX_COUNT capacity. It does support a resize via capacity() though, in circular_queue_mp this function is safe for concurrent use with multiple producers when invoked by the consumer.
I suggest that using new and delete on a small memory embedded system is not a particularly good idea, given that this leads to heap fragmentation. Which also is a weak spot of the linked-list implementation.

### CODE REVIEW

**Comment by d-a-v** [comment]
Thank for your work.
Please understand we cannot discuss of such big change right inside a PR with only me as an interlocutor.
I was just about to restore the original FIFO implementation when I saw your kind proposal.
I understand you want things to go fast and right (and I do too with this initially simple PR as a prelude for long-waiting ethernet implementation with lwIP), but this PR of mine doesn't aim at changing everything.
Let's keep things simple, simple PR for a clear view. Let me revert LIFO to FIFO and propose the regularly-function feature. 

I encourage you to make another PR after that with your proposed circular queue.

About this queue, there is a lack of comments on the API. Also the std::atomic implementation is currently unknown on esp8266 so its use needs comments. Having already std::queue, is your implementation different from it ? Many questions that need multiple views which I cannot endorse myself alone.

**Comment by dok-net** [comment]
Usually the sp_sc_queue implementations out there, having only push and pop, don't have comments on the API, either :-) I will add something in coming iterations.
All the `<atomic>` stuff is probably rather optional on the ESP8266, given that the only concurrency involves IRQs, where cache incoherency or registers aliasing are quite simpler. Um. I have interrupts turned off in all the relevant places, surrounded by `#ifdefs`. The point I am trying to prove is that a lock-free queue has no issues with interrupts, as long as the interrupts only ever take the role of (single) producer and the non-ISR code only is a consumer. As you see, this doesn't hold in the case of recurring functions, because the consumer needs to repush via `pop_revenant()` (the function's name being my IP ;-) ).

So, unless I am missing something myself, it works like this on ESP8266:
- IRQ handlers schedule functions effectively lock-free, because they run with disabled interrupts anyway.
- `run_scheduled_functions()` works lock-free, except only when a time-recurring function needs rescheduling, then it blocks IRQs for short time.
- Also any `loop()`-level scheduling of functions blocks IRQs for a short instant.

**Comment by dok-net** [comment]
Ah, and of course I should explain why I am PRing you: it's in the hope that you can do the same tests your doing for the "old" FIFO with network stack integration etc. using my PR, and giving me feedback. That's in the believe that dropping in my code is rather straightforward given this PR, if not so, mea culpa.

**Comment by d-a-v** [comment]
I am currently running your PR with my ethernet test with one `ping -i 0`, and three bulk parallel curl on a webserver.
Memory is stable, and it seems to be running as well as the current PR.
I have not tried to make other bulk scheduled function operations to shake even more this API.

**Comment by d-a-v** [comment]
@dok-net see how difficult it is for my PR to be reviewed (also privately on the maintainer chat room). I would not be able to justify it anymore with your code on top of it / repacing the current queue - that I didn't write in the first place.
This is why I can't merge your addition here and now. But my test is still running with your circular queue. The chip is hot, no hanging and no (ethernet) loss.
More serious tests will have to happen with ethernet with other scheduled-functions from irqs so to shake everything. Also an external stressing test for your class that could be run on a real multithreaded OS would encline reviewers to trust this class.

**Comment by dok-net** [comment]
@d-a-v Thanks for your well appreciated tests. I've updated this PR to merge w/o conflicts.

**Comment by d-a-v** [comment]
Are you going to move this PR to the arduino core ?

**Comment by dok-net** [comment]
You've merged everything in it, if I'm not missing anything, so I thought I'd delete the branch and PR now?

**Comment by dok-net** [comment]
Btw, the comment says "if repeat_us is 0, then the function is called only once." - is this really the case?

**Comment by d-a-v** [comment]
> is this really the case?

Not if a recurrent function ends itself. PR proposed, thanks.

**Comment by d-a-v** [comment]
> You've merged everything in 

This is the circular queue PR, not merged.

**Pull request closed without merging**
